---
- name: "Reset Kubernetes"
  shell: echo $(kubeadm reset && echo 'true') 

- name: "Remove docker images" 
  shell: echo $(docker rmi --force $(docker images --all -q) && echo 'true')
  become: true

- name: "apt-get update"
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: "apt-get purge packages"
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
    autoremove: yes
    force: yes
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - docker-ce

- name: "Remove pod logging"
  shell: rm -rf /var/log/pods/* 
  become: True

- name: Reboot
  shell: "sleep 2 && shutdown -r now"
  async: 1
  poll: 0
  ignore_errors: True

- name: Wait for Reboot
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  become: False
