---
- name: Wait for automatic system updates
  shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep; done;

- name: Ensure hostname set
  hostname: name={{ inventory_hostname }}
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: hostname
  tags: hostname

- name: Build hosts file
  lineinfile:
    dest=/etc/hosts
    regexp='.*{{ item }}$'
    line='{{ hostvars[item].ansible_default_ipv4.address }} {{item}}'
    state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups['all'] }}"
  register: hostname
  tags: hostname

- name: Add an apt key-1
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 8B48AD6246925553

- name: Add an apt key-2
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9D6D8F6BC857C906

- name: Enabling cgroup options at boot
  copy:
    src: cmdline.txt
    dest: /boot/cmdline.txt
    owner: root
    group: root
    mode: 0755
  register: cmdline
  tags:
    - boot

- name: Enable br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: apt-get update
  apt:
    update_cache=yes
    autoclean=yes
    autoremove=yes
    cache_valid_time=86400

- name: apt-get upgrade
  apt:
    upgrade=full

- name: Reboot
  shell: "sleep 2 && shutdown -r now"
  async: 1
  poll: 0
  ignore_errors: True
  when: cmdline.changed
  tags:
    - boot
    - shutdown

- name: Wait for Reboot
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  become: False
  when: cmdline.changed
  tags:
    - boot
    - shutdown
